name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Go ${{ matrix.go }} test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["stable"] # NOTE: Add "oldstable" once >=go1.25
    env:
      GOTOOLCHAIN: local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Test
        run: go test ./...
